sudo: required
services: 
    - docker

before_install:
  - docker build -t kk/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kk/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "dockerApp"
 env: "DockerApp-env"
 bucket_name: "elasticbeanstalk-us-east-1-716949460853"
 bucket_app: "docker"
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_ACCESS_SECRET